#spring.application.name=APIX
#
#spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.security.oauth2.client.registration.google.client-id=117473819696-or3ujqgurikfv0mc0jcg6ppgcbmu2i66.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#
#server.port=8080
#
#

spring.application.name=APIX

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

server.port=${PORT:8080}
